#!/usr/bin/env bash
# install nginx in a new server
sudo apt update
sudo apt -y install nginx
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo chmod 666 /usr/share/nginx/html/index.html
echo "Holberton School for the win yeah!" > /var/www/html/index.nginx-debian.html
echo "Holberton School for the win yeah!" > /usr/share/nginx/html/index.html
sudo service nginx restart
