#!/usr/bin/env bash
# Creates the process
trap "echo 'I hate the kill command'; rm '/var/run/holbertonscript.pid'; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm '/var/run/holbertonscript.pid'; exit" SIGQUIT
my_pid=$(pgrep -f "$0")
echo "$my_pid" > /var/run/holbertonscript.pid
while true
do
	echo "To infinity and beyond"
done
