#!/usr/bin/env bash
# Script to control de daemon
case $1 in
	"start")
		its_pid=$(pgrep -f manage_my_process)
		./manage_my_process &
		echo "$its_pid" > /var/run/my_process.pid
		echo "manage_my_process started"
	;;
	"stop")
		pkill its_pid
		rm -r /var/run/my_process.pid
		echo "manage_my_process stopped"
	;;
	"restart")
		pkill its_pid
		rm -r /var/run/my_process.pid
		its_pid=$(pgrep -f manage_my_process)
		./manage_my_process &
		echo "manage_my_process restarted"
	;;
	*)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
