#!/usr/bin/env bash
# This script is displaying "Holberton School" 8 times bad luck 1 time and good luck 1 time
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i=i+1))
done
