#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
hour=0
while [ $hour -lt 13 ]; do
	minutes=0
	while [ $minutes -lt 60 ]; do
		if [ $minutes -eq 0 ]
		then
			echo "Hour: $hour"
			let hour=hour+1
		else
			echo "$minutes"
		fi
		((minutes=minutes+1))
	done
done
